#!/usr/bin/env bash
###############################################################################
# lib/ca.sh - Root CA & Intermediate CAs Management, Skeletons, and Metadata
###############################################################################

CA_META_KEYS="NAME TYPE CN SUBJECT KEY KEY_PASS DAYS PATHLEN PERMIT_DNS PERMIT_IP EKU_LIMIT OCSP_URL CREATED"

# Resolves directory for a CA (root or intermediate/<name>)
ca_dir() {
    if [ "$1" = root ]; then
        printf '%s' "$PKI_DIR/root"
    else
        printf '%s' "$PKI_DIR/intermediate/$1"
    fi
}

# Checks if a CA exists
ca_exists() {
    [ -f "$(ca_dir "$1")/certs/ca.crt" ]
}

# Lists all existing Intermediate CA names
list_intermediates() {
    local d
    [ -d "$PKI_DIR/intermediate" ] || return 0
    for d in "$PKI_DIR"/intermediate/*/; do
        [ -f "$d/certs/ca.crt" ] && basename "$d"
    done
    return 0
}

# Initializes directory skeleton and OpenSSL CA configuration for a CA
make_ca_skeleton() {
    local d=$1 name=$2
    mkdir -p "$d/certs" "$d/crl" "$d/newcerts" "$d/private" "$d/archive"
    chmod 700 "$d/private"
    : > "$d/index.txt"
    printf 'unique_subject = no\n' > "$d/index.txt.attr"
    printf '1000\n' > "$d/crlnumber"

    cat > "$d/ca.cnf" <<EOF
###############################################################################
# OpenSSL CA Configuration for: $name  (generated by pki.sh $VERSION)
# Used internally by "openssl ca" (signing, revoking, CRL generation).
###############################################################################
[ ca ]
default_ca = CA_default

[ CA_default ]
dir               = $d
certs             = \$dir/certs
crl_dir           = \$dir/crl
new_certs_dir     = \$dir/newcerts
database          = \$dir/index.txt
rand_serial       = yes                 # Random 160-bit serial numbers
crlnumber         = \$dir/crlnumber
private_key       = \$dir/private/ca.key
certificate       = \$dir/certs/ca.crt
crl               = \$dir/crl/ca.crl
default_md        = default             # SHA-256 for RSA, internal digest for Ed25519
default_days      = 365
default_crl_days  = ${CRL_DAYS:-30}
crl_extensions    = crl_ext
preserve          = no
policy            = policy_loose
unique_subject    = no
copy_extensions   = none                # Enforce extensions strictly from ext.cnf
email_in_dn       = no
name_opt          = ca_default
cert_opt          = ca_default

[ policy_loose ]
countryName             = optional
stateOrProvinceName     = optional
localityName            = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

[ crl_ext ]
authorityKeyIdentifier = keyid:always
EOF
    chmod 600 "$d/ca.cnf" 2>/dev/null || true
}

# Writes metadata file for a CA
write_ca_meta() {
    local d=$1
    cat > "$d/ca.meta" <<EOF
###############################################################################
# Metadata for CA "$M_NAME" - managed by pki.sh
###############################################################################
NAME="$M_NAME"
TYPE="$M_TYPE"
CN="$M_CN"
SUBJECT="$M_SUBJECT"
KEY="$M_KEY"
KEY_PASS="$M_KEY_PASS"
DAYS="$M_DAYS"
PATHLEN="$M_PATHLEN"
PERMIT_DNS="$M_PERMIT_DNS"
PERMIT_IP="$M_PERMIT_IP"
EKU_LIMIT="$M_EKU_LIMIT"
OCSP_URL="$M_OCSP_URL"
CREATED="$M_CREATED"
EOF
    chmod 600 "$d/ca.meta" 2>/dev/null || true
}

# Loads metadata of a CA into M_* variables
load_ca_meta() {
    M_NAME="" M_TYPE="" M_CN="" M_SUBJECT="" M_KEY="" M_KEY_PASS="" M_DAYS=""
    M_PATHLEN="" M_PERMIT_DNS="" M_PERMIT_IP="" M_EKU_LIMIT="" M_OCSP_URL="" M_CREATED=""
    # shellcheck disable=SC2086
    load_kv "$(ca_dir "$1")/ca.meta" M_ $CA_META_KEYS
}

# Generates CRL Distribution Points and AIA lines for ext.cnf
aia_lines() {
    local issuer=$1 ocsp=${2:-} base=${AIA_BASE_URL%/}
    if [ -n "$base" ]; then
        printf 'crlDistributionPoints = URI:%s/%s.crl\n' "$base" "$issuer"
        if [ -n "$ocsp" ]; then
            printf 'authorityInfoAccess = OCSP;URI:%s, caIssuers;URI:%s/%s.crt\n' "$ocsp" "$base" "$issuer"
        else
            printf 'authorityInfoAccess = caIssuers;URI:%s/%s.crt\n' "$base" "$issuer"
        fi
    elif [ -n "$ocsp" ]; then
        printf 'authorityInfoAccess = OCSP;URI:%s\n' "$ocsp"
    fi
}

# Copies CA certificate and CRL to publish/ directory (in PEM and DER format)
publish_ca() {
    local ca=$1 d
    d=$(ca_dir "$ca")
    mkdir -p "$PKI_DIR/publish"
    chmod 755 "$PKI_DIR/publish" 2>/dev/null || true

    cp "$d/certs/ca.crt" "$PKI_DIR/publish/$ca.pem"
    "$OPENSSL" x509 -in "$d/certs/ca.crt" -outform der -out "$PKI_DIR/publish/$ca.crt"

    if [ -f "$d/crl/ca.crl" ]; then
        cp "$d/crl/ca.crl" "$PKI_DIR/publish/$ca.crl.pem"
        "$OPENSSL" crl -in "$d/crl/ca.crl" -outform der -out "$PKI_DIR/publish/$ca.crl"
    fi
    chmod 644 "$PKI_DIR/publish/"* 2>/dev/null || true
}

# Creates the Root CA
# Requires: R_CN R_KEY R_DAYS R_PASS(yes/no)
create_root() {
    local d="$PKI_DIR/root" subj
    [ -f "$d/certs/ca.crt" ] && die "Root CA already exists in $d"
    valid_keytype "$R_KEY" || die "Invalid key type: $R_KEY"
    is_int "$R_DAYS" || die "Validity days must be a number: $R_DAYS"
    check_safe "Root-CN" "$R_CN"

    banner "Creating Root CA: $R_CN"
    [ "$R_KEY" = ed25519 ] && warn "Ed25519 Root CA: Web browsers do NOT support Ed25519 signatures in TLS chains. For web certificates, select RSA (rsa4096)!"

    NEWPASSVAR=""
    if [ "$R_PASS" = yes ]; then
        info "The Root CA passphrase will be required whenever signing a new Intermediate CA or generating a Root CRL - store it safely!"
        ca_newpass root "the Root CA"
    fi

    # Create root directory layout
    mkdir -p "$PKI_DIR/log" "$PKI_DIR/issued" "$PKI_DIR/intermediate" "$PKI_DIR/publish" "$PKI_DIR/templates"
    write_config
    write_req_cnf

    PARTIAL_DIR=$d
    trap cleanup_partial EXIT
    make_ca_skeleton "$d" root

    gen_key "$d/private/ca.key" "$R_KEY" "$R_PASS" "$NEWPASSVAR"
    ok "Root key generated ($R_KEY$( [ "$R_PASS" = yes ] && echo ', AES-256 encrypted'))"

    cat > "$d/ext.cnf" <<EOF
###############################################################################
# Root CA Extensions
###############################################################################
[ v3_root ]
basicConstraints       = critical, CA:TRUE
keyUsage               = critical, keyCertSign, cRLSign
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always
EOF

    subj=$(build_subj "$R_CN")
    ca_passin root
    req_selfsign "$d/private/ca.key" "$subj" "$R_DAYS" "$d/ext.cnf" v3_root "$d/certs/ca.crt" "${PASSIN[@]}" \
        || die "Failed to generate Root CA certificate"
    chmod 644 "$d/certs/ca.crt"

    M_NAME=root; M_TYPE=root; M_CN=$R_CN; M_SUBJECT=$subj; M_KEY=$R_KEY; M_KEY_PASS=$R_PASS
    M_DAYS=$R_DAYS; M_PATHLEN=""; M_PERMIT_DNS=""; M_PERMIT_IP=""; M_EKU_LIMIT=""; M_OCSP_URL=""
    M_CREATED=$(now)
    write_ca_meta "$d"

    gen_crl root
    publish_ca root
    log_action "ROOT created CN='$R_CN' key=$R_KEY days=$R_DAYS"
    PARTIAL_DIR="" # Successfully finished

    ok "Root CA created successfully: $d/certs/ca.crt (valid until $(cert_end_date "$d/certs/ca.crt"))"
    info "SHA-256 Fingerprint: $(cert_fingerprint "$d/certs/ca.crt")"
}

# Writes extensions for an Intermediate CA
write_intermediate_ext() {
    local f=$1 i=0 item ip bits
    {
        printf '###############################################################################\n'
        printf '# Extensions for Intermediate CA "%s"\n' "$N_NAME"
        printf '###############################################################################\n'
        printf '[ v3_intermediate ]\n'
        printf 'basicConstraints       = critical, CA:TRUE, pathlen:%s\n' "${N_PATHLEN:-0}"
        printf 'keyUsage               = critical, digitalSignature, keyCertSign, cRLSign\n'
        printf 'subjectKeyIdentifier   = hash\n'
        printf 'authorityKeyIdentifier = keyid:always\n'
        [ -n "$N_EKU_LIMIT" ] && printf 'extendedKeyUsage       = %s\n' "$N_EKU_LIMIT"
        aia_lines root ""
        if [ -n "$N_PERMIT_DNS$N_PERMIT_IP" ]; then
            printf 'nameConstraints        = critical, @name_constraints\n'
            printf '\n[ name_constraints ]\n'
            split_list "$N_PERMIT_DNS"
            for item in "${SPLIT[@]}"; do
                printf 'permitted;DNS.%s = %s\n' "$i" "$(lower "$item")"
                i=$((i+1))
            done
            i=0
            split_list "$N_PERMIT_IP"
            for item in "${SPLIT[@]}"; do
                ip=${item%/*}; bits=${item#*/}
                [ "$bits" = "$item" ] && bits=32
                is_ipv4 "$ip" || die "nameConstraints: only IPv4 CIDR is currently supported: $item"
                printf 'permitted;IP.%s = %s/%s\n' "$i" "$ip" "$(cidr2mask "$bits")"
                i=$((i+1))
            done
        fi
    } > "$f"
}

# Creates a new Intermediate CA
# Requires: N_NAME N_CN N_KEY N_DAYS N_PASS N_PATHLEN N_PERMIT_DNS N_PERMIT_IP N_EKU_LIMIT N_OCSP_URL
create_intermediate() {
    local d subj
    is_name "$N_NAME" || die "Invalid CA name '$N_NAME' (allowed: a-z 0-9 . _ -)"
    [ "$N_NAME" = root ] || [ "$N_NAME" = selfsigned ] && die "The name '$N_NAME' is reserved"
    d=$(ca_dir "$N_NAME")
    [ -e "$d/certs/ca.crt" ] && die "Intermediate CA '$N_NAME' already exists"

    [ -z "$N_KEY" ]  && N_KEY=$DEFAULT_CA_KEY
    [ -z "$N_DAYS" ] && N_DAYS=$INTERMEDIATE_DAYS
    [ -z "$N_CN" ]   && N_CN="$PKI_ORG $N_NAME"
    valid_keytype "$N_KEY" || die "Invalid key type: $N_KEY"
    is_int "$N_DAYS" || die "Validity days must be a number: $N_DAYS"
    is_int "${N_PATHLEN:-0}" || die "pathlen must be an integer"
    check_safe "CN" "$N_CN"

    local rootleft
    rootleft=$(cert_days_left "$PKI_DIR/root/certs/ca.crt")
    if [ "$N_DAYS" -gt "$rootleft" ]; then
        warn "Validity shortened to Root CA remaining lifetime: $rootleft days"
        N_DAYS=$rootleft
    fi

    banner "Creating Intermediate CA: $N_NAME"
    [ "$N_KEY" = ed25519 ] && warn "Ed25519 CA: Web browsers cannot verify Ed25519 chains. Only suitable for non-browser purposes (VPN, internal microservices, mTLS)."

    # Resolve passwords in advance
    if key_is_encrypted "$PKI_DIR/root/private/ca.key"; then
        info "Root CA authorization required to sign the new Intermediate CA:"
        ca_passin root
    fi
    NEWPASSVAR=""
    [ "$N_PASS" = yes ] && ca_newpass "$N_NAME" "the Intermediate CA '$N_NAME'"

    [ -d "$d" ] && rm -rf "$d"
    PARTIAL_DIR=$d
    trap cleanup_partial EXIT

    make_ca_skeleton "$d" "$N_NAME"
    gen_key "$d/private/ca.key" "$N_KEY" "$N_PASS" "$NEWPASSVAR"
    write_intermediate_ext "$d/ext.cnf"

    subj=$(build_subj "$N_CN")
    ca_passin "$N_NAME"
    ssl req -new -utf8 -config "$PKI_DIR/.req.cnf" -key "$d/private/ca.key" "${PASSIN[@]}" -subj "$subj" -out "$d/ca.csr" \
        || die "CSR creation for Intermediate CA failed"

    ca_passin root
    ssl ca -batch -config "$PKI_DIR/root/ca.cnf" "${PASSIN[@]}" -extfile "$d/ext.cnf" -extensions v3_intermediate \
        -days "$N_DAYS" -notext -preserveDN -in "$d/ca.csr" -out "$d/certs/ca.crt" \
        || die "Signing by Root CA failed"
    ok "Signed by Root CA"
    chmod 644 "$d/certs/ca.crt"

    # Create full chain (Intermediate + Root)
    cat "$d/certs/ca.crt" "$PKI_DIR/root/certs/ca.crt" > "$d/certs/chain.pem"
    chmod 644 "$d/certs/chain.pem"

    M_NAME=$N_NAME; M_TYPE=intermediate; M_CN=$N_CN; M_SUBJECT=$subj; M_KEY=$N_KEY; M_KEY_PASS=$N_PASS
    M_DAYS=$N_DAYS; M_PATHLEN=${N_PATHLEN:-0}; M_PERMIT_DNS=$N_PERMIT_DNS; M_PERMIT_IP=$N_PERMIT_IP
    M_EKU_LIMIT=$N_EKU_LIMIT; M_OCSP_URL=$N_OCSP_URL; M_CREATED=$(now)
    write_ca_meta "$d"

    gen_crl "$N_NAME"
    gen_crl root
    publish_ca "$N_NAME"

    PARTIAL_DIR="" # Successfully completed

    if [ -z "$DEFAULT_CA" ]; then
        DEFAULT_CA=$N_NAME
        write_config
        info "Set as default CA (DEFAULT_CA in pki.conf)"
    fi

    log_action "INTERMEDIATE created name=$N_NAME CN='$N_CN' key=$N_KEY days=$N_DAYS"
    ok "Intermediate CA '$N_NAME' created successfully (valid until $(cert_end_date "$d/certs/ca.crt"))"
}
