#!/usr/bin/env bash
###############################################################################
# lib/config.sh - PKI configuration management and safe Key/Value file parsing
###############################################################################

CONF_KEYS="PKI_COUNTRY PKI_STATE PKI_LOCALITY PKI_ORG PKI_OU DEFAULT_CA DEFAULT_LEAF_KEY DEFAULT_CA_KEY ROOT_DAYS INTERMEDIATE_DAYS CRL_DAYS AIA_BASE_URL WARN_DAYS"

# Default settings for a new PKI
set_conf_defaults() {
    PKI_COUNTRY="US"
    PKI_STATE=""
    PKI_LOCALITY=""
    PKI_ORG="Homelab"
    PKI_OU=""
    DEFAULT_CA=""
    DEFAULT_LEAF_KEY="rsa3072"
    DEFAULT_CA_KEY="rsa4096"
    ROOT_DAYS=7300
    INTERMEDIATE_DAYS=3650
    CRL_DAYS=30
    AIA_BASE_URL=""
    WARN_DAYS=30
}

# Safely parse Key/Value files (pki.conf, cert.meta, ca.meta, templates).
# Files are NEVER executed with "source". Only whitelisted keys are ingested.
load_kv() {
    local file=$1 prefix=$2; shift 2
    local allowed=" $* " line key val re='^[[:space:]]*([A-Z_][A-Z0-9_]*)[[:space:]]*=(.*)$'
    local reDq='^"([^"]*)"' reSq="^'([^']*)'"
    [ -r "$file" ] || die "File not readable: $file"
    while IFS= read -r line || [ -n "$line" ]; do
        line=${line%$'\r'}
        case $(trim "$line") in ''|'#'*) continue;; esac
        if ! [[ $line =~ $re ]]; then warn "$file: ignored line: $line"; continue; fi
        key=${BASH_REMATCH[1]}; val=$(trim "${BASH_REMATCH[2]}")
        if   [[ $val =~ $reDq ]]; then val=${BASH_REMATCH[1]}
        elif [[ $val =~ $reSq ]]; then val=${BASH_REMATCH[1]}
        else val=$(trim "${val%%#*}"); fi
        case $allowed in
            *" $key "*) printf -v "${prefix}${key}" '%s' "$val" ;;
            *) warn "$file: unknown key '$key' ignored" ;;
        esac
    done < "$file"
}

# Load global configuration from $PKI_DIR/pki.conf
load_config() {
    set_conf_defaults
    # shellcheck disable=SC2086
    [ -f "$PKI_DIR/pki.conf" ] && load_kv "$PKI_DIR/pki.conf" "" $CONF_KEYS
    return 0
}

# Write global configuration to $PKI_DIR/pki.conf
write_config() {
    mkdir -p "$PKI_DIR"
    cat > "$PKI_DIR/pki.conf" <<EOF
###############################################################################
# pki.conf - Global PKI configuration (generated by pki.sh $VERSION)
# Format: KEY="value" - Safely parsed, not executed as shell script.
###############################################################################

######## Subject fields inherited by new certificates
PKI_COUNTRY="$PKI_COUNTRY"          # 2-letter country code (ISO 3166-1 alpha-2)
PKI_STATE="$PKI_STATE"              # State or Province (optional)
PKI_LOCALITY="$PKI_LOCALITY"        # City / Locality (optional)
PKI_ORG="$PKI_ORG"                  # Organization name
PKI_OU="$PKI_OU"                    # Organizational Unit (optional)

######## Default settings
DEFAULT_CA="$DEFAULT_CA"            # Intermediate CA used when --ca is omitted
DEFAULT_LEAF_KEY="$DEFAULT_LEAF_KEY"   # rsa2048 | rsa3072 | rsa4096 | ed25519
DEFAULT_CA_KEY="$DEFAULT_CA_KEY"       # Default key type for new CAs
ROOT_DAYS="$ROOT_DAYS"              # Validity of Root CA in days
INTERMEDIATE_DAYS="$INTERMEDIATE_DAYS"  # Validity of Intermediate CAs in days
CRL_DAYS="$CRL_DAYS"                # Validity of CRLs - regenerate before expiry!
WARN_DAYS="$WARN_DAYS"              # Days before expiration to trigger warnings

######## Publishing (optional)
# Base HTTP URL hosting publish/ directory (CRL Distribution Point & AIA caIssuers)
# e.g., http://pki.lan -> http://pki.lan/server-ca.crl
AIA_BASE_URL="$AIA_BASE_URL"
EOF
    chmod 600 "$PKI_DIR/pki.conf" 2>/dev/null || true
}

# Ensure PKI has been initialized
require_pki() {
    [ -f "$PKI_DIR/root/certs/ca.crt" ] || die "No PKI found in $PKI_DIR. Initialize first: pki init (or set --dir / \$PKI_DIR)"
}

# Read single key from a .meta file
meta_get() {
    awk -F'"' -v k="$2" '$0 ~ "^"k"=" {print $2; exit}' "$1/cert.meta" 2>/dev/null
}
