#!/usr/bin/env bash
###############################################################################
# lib/crypto.sh - OpenSSL 3.x discovery, invocation, and cryptographic helpers
###############################################################################

# Discover OpenSSL 3.x in PATH or common installation locations
find_openssl() {
    local c
    for c in "${OPENSSL:-}" openssl /opt/homebrew/opt/openssl@3/bin/openssl \
             /usr/local/opt/openssl@3/bin/openssl /usr/bin/openssl /usr/local/bin/openssl; do
        [ -n "$c" ] || continue
        command -v "$c" >/dev/null 2>&1 || continue
        if "$c" version 2>/dev/null | grep -q '^OpenSSL 3'; then
            OPENSSL=$(command -v "$c")
            return 0
        fi
    done
    die "OpenSSL 3.x not found (LibreSSL is not supported).
  Linux: Install package 'openssl' (v3).
  macOS: 'brew install openssl@3'.
  Or set path manually: OPENSSL=/path/to/openssl"
}

# Run OpenSSL commands. Captures and formats errors nicely.
# When PKI_DEBUG=1 is set, all output is printed.
ssl() {
    local out rc=0
    out=$("$OPENSSL" "$@" 2>&1) || rc=$?
    if [ "$rc" -ne 0 ]; then
        err "openssl $1 failed (Exit $rc):"
        printf '%s\n' "$out" | sed 's/^/        /' >&2
        return "$rc"
    fi
    if [ "${PKI_DEBUG:-0}" = 1 ] && [ -n "$out" ]; then
        printf '%s\n' "$out" | sed 's/^/    [openssl] /' >&2
    fi
    return 0
}

# Validate supported key algorithms
valid_keytype() {
    case $1 in
        rsa2048|rsa3072|rsa4096|ed25519) return 0 ;;
        *) return 1 ;;
    esac
}

# Generate private key
#   gen_key <output> <type> <yes|no encrypt> <ENV-Var with password>
gen_key() {
    local out=$1 type=$2 enc=$3 passvar=${4:-} args=()
    case $type in
        rsa2048|rsa3072|rsa4096)
            args=(-algorithm RSA -pkeyopt "rsa_keygen_bits:${type#rsa}")
            ;;
        ed25519)
            args=(-algorithm ED25519)
            ;;
        *)
            die "Unknown key type '$type' (allowed: rsa2048, rsa3072, rsa4096, ed25519)"
            ;;
    esac

    if [ "$enc" = yes ]; then
        args+=(-aes-256-cbc)
        [ -n "$passvar" ] && [ -n "${!passvar:-}" ] || die "Internal error: no password provided for key generation"
        args+=(-pass "env:$passvar")
    fi

    ssl genpkey "${args[@]}" -out "$out" || die "Failed to generate key: $out"
    chmod 600 "$out"
}

# Certificate end date in Epoch seconds
cert_end_epoch() {
    local d; d=$("$OPENSSL" x509 -in "$1" -noout -enddate -dateopt iso_8601 2>/dev/null) || return 1
    d=${d#notAfter=}; to_epoch "${d%Z}"
}

# Expiration date formatted as YYYY-MM-DD
cert_end_date() {
    local d; d=$("$OPENSSL" x509 -in "$1" -noout -enddate -dateopt iso_8601 2>/dev/null) || { printf '?'; return; }
    d=${d#notAfter=}; printf '%s' "${d%% *}"
}

# Remaining validity in days (negative = expired)
cert_days_left() {
    local e; e=$(cert_end_epoch "$1") || { printf '?'; return; }
    printf '%s' $(( (e - $(date -u +%s)) / 86400 ))
}

# Certificate serial number
cert_serial() {
    local s; s=$("$OPENSSL" x509 -in "$1" -noout -serial)
    printf '%s' "${s#serial=}"
}

# Extract Common Name (CN) from certificate
cert_cn() {
    "$OPENSSL" x509 -in "$1" -noout -subject -nameopt multiline,utf8,-esc_msb 2>/dev/null \
        | awk -F' = ' '/commonName/{print $2; exit}'
}

# SHA-256 fingerprint
cert_fingerprint() {
    "$OPENSSL" x509 -in "$1" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2
}

# Status of serial in CA index database: V (valid) / R (revoked) / E (expired) / ""
index_status() {
    awk -F'\t' -v s="$2" '
        function norm(x){ x=toupper(x); sub(/^0+/,"",x); return x }
        norm($4)==norm(s){ st=$1 } END{ print st }' "$1/index.txt"
}

# Build subject DN string for openssl -subj
build_subj() {
    local s=""
    [ -n "$PKI_COUNTRY" ]  && s="$s/C=$(dn_escape "$PKI_COUNTRY")"
    [ -n "$PKI_STATE" ]    && s="$s/ST=$(dn_escape "$PKI_STATE")"
    [ -n "$PKI_LOCALITY" ] && s="$s/L=$(dn_escape "$PKI_LOCALITY")"
    [ -n "$PKI_ORG" ]      && s="$s/O=$(dn_escape "$PKI_ORG")"
    [ -n "${2:-$PKI_OU}" ] && s="$s/OU=$(dn_escape "${2:-$PKI_OU}")"
    s="$s/CN=$(dn_escape "$1")"
    printf '%s' "$s"
}

# Minimal req configuration (avoids dependency on host /etc/ssl/openssl.cnf)
write_req_cnf() {
    mkdir -p "$PKI_DIR"
    cat > "$PKI_DIR/.req.cnf" <<'EOF'
# Minimal OpenSSL configuration for "openssl req" - generated by pki.sh
[ req ]
distinguished_name = req_dn
string_mask        = utf8only
utf8               = yes
prompt             = no
[ req_dn ]
CN = placeholder
EOF
    chmod 600 "$PKI_DIR/.req.cnf" 2>/dev/null || true
}

# Generate self-signed certificate (Root CA or --ca selfsigned)
# Combines .req.cnf + extension file for backwards compatibility with OpenSSL < 3.2
#   req_selfsign <key> <subj> <days> <extfile> <section> <out> [passin-args...]
req_selfsign() {
    local key=$1 subj=$2 days=$3 ext=$4 sect=$5 out=$6 tmp rc=0; shift 6
    tmp=$(mktemp "${TMPDIR:-/tmp}/pki-req.XXXXXX")
    cat "$PKI_DIR/.req.cnf" "$ext" > "$tmp"
    ssl req -x509 -new -utf8 -config "$tmp" -key "$key" "$@" -subj "$subj" -days "$days" \
        -extensions "$sect" -out "$out" || rc=$?
    rm -f "$tmp"
    return $rc
}
