#!/usr/bin/env bash
###############################################################################
# lib/issue.sh - Leaf Certificate Issuance, SAN Normalization, and Bundles
###############################################################################

I_KEYS="PRESET NAME CN DNS IP EMAIL URI KEY DAYS CA OU KEY_PASS EXPORT_P12 EXPORT_DER P12_LEGACY CUSTOM_KU CUSTOM_EKU"

# Resets all variables for certificate issuance
reset_issue_vars() {
    I_PRESET="" I_NAME="" I_CN="" I_DNS="" I_IP="" I_EMAIL="" I_URI="" I_KEY=""
    I_DAYS="" I_CA="" I_OU="" I_KEY_PASS=no I_EXPORT_P12=no I_EXPORT_DER=no I_P12_LEGACY=no
    I_CUSTOM_KU="" I_CUSTOM_EKU="" I_DOMAIN=""
    I_FORCE=0 I_RENEW=0 I_KEEP_KEY=0 I_CSR_FILE=""
}

# Checks and normalizes SANs (lowercase DNS, deduplicate, move IPs from DNS field)
normalize_sans() {
    local x dns="" ip="" email="" uri="" cn
    # Modern TLS clients ignore CN if SAN is present; ensure CN is in SAN
    case $P_CN_AUTO in
        dns)
            cn=$(lower "$I_CN")
            if is_ipv4 "$cn" || is_ipv6 "$cn"; then
                ip=$cn; I_CN=$cn
            elif is_hostname "$cn"; then
                dns=$cn; I_CN=$cn
            fi
            ;;
        email)
            is_email "$I_CN" && email=$(lower "$I_CN")
            ;;
    esac

    split_list "$I_DNS"
    for x in "${SPLIT[@]}"; do
        x=$(lower "$x"); x=${x%.}
        if is_ipv4 "$x" || is_ipv6 "$x"; then
            warn "'$x' is an IP address -> automatically added as IP SAN"
            ip=$(add_uniq "$ip" "$x")
            continue
        fi
        is_hostname "$x" || die "Invalid DNS name: '$x'"
        dns=$(add_uniq "$dns" "$x")
    done

    split_list "$I_IP"
    for x in "${SPLIT[@]}"; do
        x=$(lower "$x")
        is_ipv4 "$x" || is_ipv6 "$x" || die "Invalid IP address: '$x'"
        ip=$(add_uniq "$ip" "$x")
    done

    split_list "$I_EMAIL"
    for x in "${SPLIT[@]}"; do
        x=$(lower "$x")
        is_email "$x" || die "Invalid email address: '$x'"
        email=$(add_uniq "$email" "$x")
    done

    split_list "$I_URI"
    for x in "${SPLIT[@]}"; do
        is_uri "$x" || die "Invalid URI: '$x'"
        uri=$(add_uniq "$uri" "$x")
    done

    I_DNS=$dns
    I_IP=$ip
    I_EMAIL=$email
    I_URI=$uri
}

# Validates Name Constraints against issuing CA prior to signing
check_name_constraints() {
    local ca=$1 x c ok bits net mask
    load_ca_meta "$ca"

    if [ -n "$M_PERMIT_DNS" ]; then
        split_list "$I_DNS"
        for x in "${SPLIT[@]}"; do
            ok=0; x=${x#\*.}
            for c in $(printf '%s' "$M_PERMIT_DNS" | tr ',' ' '); do
                c=$(lower "$c")
                case $c in
                    .*) case $x in *"$c") ok=1 ;; esac ;;
                    *)  [ "$x" = "$c" ] && ok=1; case $x in *".$c") ok=1 ;; esac ;;
                esac
            done
            [ "$ok" = 1 ] || die "DNS '$x' violates Name Constraints of CA '$ca' (Permitted: $M_PERMIT_DNS)"
        done
    fi

    if [ -n "$M_PERMIT_IP" ]; then
        split_list "$I_IP"
        for x in "${SPLIT[@]}"; do
            is_ipv4 "$x" || die "IP '$x' violates Name Constraints of CA '$ca' (Only IPv4 supported: $M_PERMIT_IP)"
            ok=0
            for c in $(printf '%s' "$M_PERMIT_IP" | tr ',' ' '); do
                net=${c%/*}; bits=${c#*/}; [ "$bits" = "$c" ] && bits=32
                mask=$(( bits == 0 ? 0 : (0xFFFFFFFF << (32-bits)) & 0xFFFFFFFF ))
                [ $(( $(ip2int "$x") & mask )) -eq $(( $(ip2int "$net") & mask )) ] && ok=1
            done
            [ "$ok" = 1 ] || die "IP '$x' violates Name Constraints of CA '$ca' (Permitted: $M_PERMIT_IP)"
        done
    fi
    return 0
}

# Generates extension configuration file for a leaf certificate
write_leaf_ext() {
    local f=$1 issuer=$2 ocsp=$3 ku eku x n
    if [ "$I_KEY" = ed25519 ]; then ku=$P_KU_ED; else ku=$P_KU_RSA; fi
    eku=$P_EKU

    {
        printf '###############################################################################\n'
        printf '# Extensions for "%s" (Preset: %s, CA: %s)\n' "$I_NAME" "$I_PRESET" "$issuer"
        printf '# Generated by pki.sh %s on %s\n' "$VERSION" "$(now)"
        printf '###############################################################################\n'
        printf '[ leaf_ext ]\n'
        printf 'basicConstraints       = critical, CA:FALSE\n'
        [ -n "$ku" ]  && printf 'keyUsage               = critical, %s\n' "$ku"
        if [ -n "$eku" ]; then
            if [ "$P_EKU_CRIT" = yes ]; then
                printf 'extendedKeyUsage       = critical, %s\n' "$eku"
            else
                printf 'extendedKeyUsage       = %s\n' "$eku"
            fi
        fi
        printf 'subjectKeyIdentifier   = hash\n'
        if [ "$issuer" != selfsigned ]; then
            printf 'authorityKeyIdentifier = keyid:always\n'
            if [ "$I_PRESET" = ocsp ]; then
                aia_lines "$issuer" ""
            else
                aia_lines "$issuer" "$ocsp"
            fi
        fi
        [ -n "$P_EXTRA" ] && printf '%s\n' "$P_EXTRA"
        if [ -n "$I_DNS$I_IP$I_EMAIL$I_URI" ]; then
            printf 'subjectAltName         = @alt_names\n\n[ alt_names ]\n'
            n=1; split_list "$I_DNS";   for x in "${SPLIT[@]}"; do printf 'DNS.%s   = %s\n' "$n" "$x"; n=$((n+1)); done
            n=1; split_list "$I_IP";    for x in "${SPLIT[@]}"; do printf 'IP.%s    = %s\n' "$n" "$x"; n=$((n+1)); done
            n=1; split_list "$I_EMAIL"; for x in "${SPLIT[@]}"; do printf 'email.%s = %s\n' "$n" "$x"; n=$((n+1)); done
            n=1; split_list "$I_URI";   for x in "${SPLIT[@]}"; do printf 'URI.%s   = %s\n' "$n" "$x"; n=$((n+1)); done
        fi
    } > "$f"
}

# Writes metadata file (also serves as reproducible template for renewal and batch issuing)
write_cert_meta() {
    local target=$1 certfile=$2
    cat > "$target" <<EOF
###############################################################################
# Metadata for "$I_NAME" - managed by pki.sh
# This file can be used as a template: pki batch <file>
###############################################################################
PRESET="$I_PRESET"
NAME="$I_NAME"
CN="$I_CN"
OU="$I_OU"
DNS="$I_DNS"
IP="$I_IP"
EMAIL="$I_EMAIL"
URI="$I_URI"
KEY="$I_KEY"
DAYS="$I_DAYS"
CA="$I_CA"
KEY_PASS="$I_KEY_PASS"
EXPORT_P12="$I_EXPORT_P12"
EXPORT_DER="$I_EXPORT_DER"
P12_LEGACY="$I_P12_LEGACY"
CUSTOM_KU="$I_CUSTOM_KU"
CUSTOM_EKU="$I_CUSTOM_EKU"
ISSUED="$(now)"
SERIAL="$(cert_serial "$certfile")"
EOF
    chmod 600 "$target" 2>/dev/null || true
}

# Generates certificate chains and bundle files
write_bundles() {
    local d=$1 ca=$2 cad
    if [ "$ca" = selfsigned ]; then
        : > "$d/chain.pem"
        cp "$d/cert.pem" "$d/fullchain.pem"
        cp "$d/cert.pem" "$d/ca-bundle.pem"
    elif [ "$ca" = root ]; then
        : > "$d/chain.pem"
        cp "$d/cert.pem" "$d/fullchain.pem"
        cp "$PKI_DIR/root/certs/ca.crt" "$d/ca-bundle.pem"
    else
        cad=$(ca_dir "$ca")
        cp "$cad/certs/ca.crt" "$d/chain.pem"
        cat "$d/cert.pem" "$cad/certs/ca.crt" > "$d/fullchain.pem"
        cp "$cad/certs/chain.pem" "$d/ca-bundle.pem"
    fi

    # Combined bundle for HAProxy
    if [ -f "$d/key.pem" ]; then
        cat "$d/key.pem" "$d/fullchain.pem" > "$d/combined.pem"
        chmod 600 "$d/combined.pem"
    fi
    chmod 644 "$d/cert.pem" "$d/chain.pem" "$d/fullchain.pem" "$d/ca-bundle.pem" 2>/dev/null || true
}

# Archives previous certificate material during renewal
archive_leaf() {
    local d=$1 keep_key=$2 a f
    a="$d/archive/$(stamp)"
    mkdir -p "$a"
    for f in "$d"/*; do
        [ -f "$f" ] || continue
        if [ "$keep_key" = 1 ] && [ "$(basename "$f")" = key.pem ]; then
            cp "$f" "$a/"
            continue
        fi
        mv "$f" "$a/"
    done
    info "Previous certificate material archived: ${a#"$PKI_DIR"/}"
}

# Main issuance function
issue_cert() {
    local d cad subj ocsp="" left
    load_preset "$I_PRESET" || die "Unknown preset '$I_PRESET'. Available presets: $PRESETS"

    if [ "$I_PRESET" = custom ]; then
        [ -n "$I_CUSTOM_KU$I_CUSTOM_EKU" ] || die "Custom preset requires --ku and/or --eku"
        P_KU_RSA=$I_CUSTOM_KU; P_KU_ED=$I_CUSTOM_KU; P_EKU=$I_CUSTOM_EKU
    fi

    [ -z "$I_KEY" ]  && I_KEY=$DEFAULT_LEAF_KEY
    [ -z "$I_DAYS" ] && I_DAYS=$P_DAYS
    [ -z "$I_CA" ]   && I_CA=$DEFAULT_CA
    [ -z "$I_CA" ]   && die "No CA specified and no DEFAULT_CA set (--ca <name>)"
    valid_keytype "$I_KEY" || die "Invalid key type: $I_KEY"
    is_int "$I_DAYS" && [ "$I_DAYS" -gt 0 ] || die "Invalid validity in days: $I_DAYS"

    # Wildcard: construct CN and SANs from --domain
    if [ "$I_PRESET" = wildcard ]; then
        if [ -n "$I_DOMAIN" ]; then
            I_DOMAIN=$(lower "${I_DOMAIN#\*.}")
            I_CN="*.$I_DOMAIN"
        fi
        case $I_CN in
            \*.*) ;;
            *) die "Wildcard certificate requires --domain <domain> or --cn '*.<domain>'" ;;
        esac
        I_DNS=$(add_uniq "$I_DNS" "$(lower "$I_CN")")
        I_DNS=$(add_uniq "$I_DNS" "$(lower "${I_CN#\*.}")")
    fi

    [ -n "$I_CN" ] || die "No Common Name (--cn) specified"
    check_safe "CN" "$I_CN"; check_safe "OU" "$I_OU"
    [ "$I_CN" = "$(trim "$I_CN")" ] || I_CN=$(trim "$I_CN")

    normalize_sans

    case $P_SAN_REQ in
        "dns|ip") [ -n "$I_DNS$I_IP" ] || die "Preset '$I_PRESET' requires at least one DNS or IP SAN (--dns / --ip)" ;;
        email)    [ -n "$I_EMAIL" ]    || die "Preset '$I_PRESET' requires at least one email address (--email)" ;;
    esac

    # Ed25519 compatibility notice
    if [ "$I_KEY" = ed25519 ]; then
        case $I_PRESET in
            server|wildcard|server-client)
                warn "Ed25519 TLS server certificates are NOT supported by standard browsers (Chrome/Firefox/Safari)! Only use for internal APIs, CLI tools, or mutual TLS." ;;
            smime|user)
                warn "Ed25519 does not support key encryption (signatures only). For S/MIME email protection, RSA is recommended." ;;
            vpn-server|vpn-client)
                warn "Ed25519 with IPsec: Standard Windows/macOS built-in clients do not support it. OpenVPN and strongSwan do." ;;
            codesign)
                warn "Ed25519 is not supported by Microsoft Authenticode." ;;
        esac
    fi

    case $I_PRESET in
        server|wildcard|server-client|vpn-server)
            [ "$I_DAYS" -gt 825 ] && warn "Apple (macOS/iOS) rejects TLS server certificates with validity exceeding 825 days." ;;
    esac

    [ -z "$I_NAME" ] && I_NAME=$(name_from_cn "$I_CN")
    I_NAME=$(lower "$I_NAME")
    is_name "$I_NAME" || die "Invalid certificate name '$I_NAME' (allowed: a-z 0-9 . _ @ -)"
    d="$PKI_DIR/issued/$I_NAME"

    # Verify issuing CA
    if [ "$I_CA" != selfsigned ]; then
        ca_exists "$I_CA" || die "CA '$I_CA' does not exist. Available CAs: root $(list_intermediates | tr '\n' ' ')"
        cad=$(ca_dir "$I_CA")
        [ "$I_CA" = root ] && warn "Issuing directly from Root CA - recommended best practice is using an Intermediate CA."
        left=$(cert_days_left "$cad/certs/ca.crt")
        [ "$left" -le 0 ] && die "The issuing CA '$I_CA' has expired!"
        if [ "$I_DAYS" -gt "$left" ]; then
            warn "Certificate validity shortened to CA remaining lifetime: $left days"
            I_DAYS=$left
        fi
        check_name_constraints "$I_CA"
        load_ca_meta "$I_CA"
        ocsp=$M_OCSP_URL
    fi

    if [ -e "$d/cert.pem" ] && [ "$I_RENEW" != 1 ] && [ "$I_FORCE" != 1 ]; then
        die "Certificate '$I_NAME' already exists. Use --force to overwrite or run: pki renew $I_NAME"
    fi

    banner "Issuing Certificate: $I_NAME  [$I_PRESET]"
    kv "Common Name" "$I_CN"
    kv "Issuer"      "$I_CA"
    [ -n "$I_DNS" ]   && kv "DNS SANs"   "$(printf '%s' "$I_DNS"   | sed 's/,/, /g')"
    [ -n "$I_IP" ]    && kv "IP SANs"    "$(printf '%s' "$I_IP"    | sed 's/,/, /g')"
    [ -n "$I_EMAIL" ] && kv "Email"      "$(printf '%s' "$I_EMAIL" | sed 's/,/, /g')"
    [ -n "$I_URI" ]   && kv "URI"        "$(printf '%s' "$I_URI"   | sed 's/,/, /g')"
    if [ -n "$I_CSR_FILE" ]; then
        kv "Key" "Private key remains with requester (external CSR)"
    else
        kv "Key" "$I_KEY, $( [ "$I_KEY_PASS" = yes ] && echo 'encrypted with passphrase' || echo 'unencrypted')"
    fi
    kv "Validity"    "$I_DAYS days"
    printf '\n' >&2

    if [ "$I_KEY_PASS" = yes ]; then
        case $I_PRESET in
            server|wildcard|server-client|vpn-server|ocsp|timestamp)
                warn "Passphrase-encrypted private key: Services like Nginx, Apache, or Docker cannot restart unattended without password entry." ;;
        esac
    fi

    # Resolve passwords in advance
    [ "$I_CA" != selfsigned ] && ca_passin "$I_CA"
    if [ "$I_KEEP_KEY" = 1 ] && [ -f "$d/key.pem" ]; then
        key_passin "$d/key.pem"
    elif [ -z "$I_CSR_FILE" ] && [ "$I_KEY_PASS" = yes ] && [ -z "${PKI_KEY_PASS:-}" ]; then
        new_pass PKI_KEY_PASS "the private key of '$I_NAME'"
    fi
    [ "$I_EXPORT_P12" = yes ] && ensure_p12_pass

    if [ -e "$d/cert.pem" ]; then
        archive_leaf "$d" "$I_KEEP_KEY"
    fi
    mkdir -p "$d"

    STEP_N=0; STEP_TOTAL=5
    step "Input parameters verified"

    # 1) Generate or adopt private key
    if [ -n "$I_CSR_FILE" ]; then
        cp "$I_CSR_FILE" "$d/cert.csr"
        step "External CSR imported"
    else
        if [ "$I_KEEP_KEY" = 1 ] && [ -f "$d/key.pem" ]; then
            step "Reusing existing private key"
        else
            gen_key "$d/key.pem" "$I_KEY" "$I_KEY_PASS" PKI_KEY_PASS
            step "Private key generated ($I_KEY)"
        fi
    fi

    # 2) CSR and Extensions
    subj=$(build_subj "$I_CN" "$I_OU")
    write_leaf_ext "$d/ext.cnf" "$I_CA" "$ocsp"

    if [ "$I_CA" = selfsigned ]; then
        key_passin "$d/key.pem"
        req_selfsign "$d/key.pem" "$subj" "$I_DAYS" "$d/ext.cnf" leaf_ext "$d/cert.pem" "${KPASSIN[@]}" \
            || die "Failed to generate self-signed certificate"
        step "Self-signed certificate created (Serial $(cert_serial "$d/cert.pem"))"
    else
        if [ -z "$I_CSR_FILE" ]; then
            key_passin "$d/key.pem"
            ssl req -new -utf8 -config "$PKI_DIR/.req.cnf" -key "$d/key.pem" "${KPASSIN[@]}" -subj "$subj" -out "$d/cert.csr" \
                || die "CSR generation failed"
        fi
        ca_passin "$I_CA"
        ssl ca -batch -config "$cad/ca.cnf" "${PASSIN[@]}" -extfile "$d/ext.cnf" -extensions leaf_ext \
            -days "$I_DAYS" -notext -preserveDN -utf8 -subj "$subj" -in "$d/cert.csr" -out "$d/cert.pem" \
            || die "Signing by CA '$I_CA' failed"
        step "Signed by CA '$I_CA' (Serial $(cert_serial "$d/cert.pem"))"
    fi

    write_bundles "$d" "$I_CA"
    write_cert_meta "$d/cert.meta" "$d/cert.pem"

    [ "$I_EXPORT_P12" = yes ] && export_p12 "$I_NAME"
    [ "$I_EXPORT_DER" = yes ] && export_der "$I_NAME"
    step "Certificate chains & bundles generated"

    write_howto "$d"
    step "Ready to deploy! Documentation written to GUIDE.txt"

    log_action "ISSUE name=$I_NAME preset=$I_PRESET ca=$I_CA cn='$I_CN' serial=$(cert_serial "$d/cert.pem") dns='$I_DNS' ip='$I_IP' email='$I_EMAIL'"

    print_quick_usage "$d"
}
